#https://github.com/realm/SwiftLint
excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods
whitelist_rules:
 - class_delegate_protocol
 - closing_brace
 - closure_parameter_position
 - closure_spacing
 - colon
 - comma
 - compiler_protocol_init
 - control_statement
 - dynamic_inline
 - empty_count
 - empty_parameters
 - empty_parentheses_with_trailing_closure
 - force_cast
 - force_try
 - force_unwrapping
 #- function_parameter_count
 - generic_type_name
 #- identifier_name
 - implicit_getter
 - implicitly_unwrapped_optional
 - leading_whitespace
 - legacy_cggeometry_functions
 - legacy_constant
 - legacy_constructor
 - legacy_nsgeometry_functions
 - mark
 - nesting
 - opening_brace
# - operator_usage_whitespace
 - operator_whitespace
 - overridden_super_call
 - private_unit_test
 - redundant_nil_coalescing
 # - redundant_optional_initialization
 - redundant_string_enum_value
 - redundant_void_return
 - return_arrow_whitespace
 - shorthand_operator
 - sorted_imports
 - statement_position
 - switch_case_on_newline
 - syntactic_sugar
 - todo
 - trailing_comma
 - trailing_newline
 - trailing_semicolon
 - trailing_whitespace
 - unused_closure_parameter
 - unused_enumerated
 - unused_optional_binding
 - valid_ibinspectable
 #- vertical_parameter_alignment
 - vertical_whitespace
 - void_return
 - weak_delegate
